### ISSUE TITLE
LZW no longer working?

### ISSUE THREAD

**Issue by juckele** [NTT123/LZW#1]
It seems like after the few updates from Leela Zero, the web version has gotten too out of sync. I really enjoyed having it as a pseudo screen saver and it made my work computer contribute more than it otherwise could. I'd love to see an updated version for the web :)

Symptoms: Text on page is present, but the space the go board is in is empty (white), with a time bar always showing full time remaining for the next move.

**Comment by NTT123** [comment]
Thanks. It's working now ;)
